require "highline"
require 'io/console'
require 'yaml'
require 'typingtutor/version'
require 'typingtutor/stats'
require 'typingtutor/dictionary'
require 'typingtutor/line'
require 'typingtutor/exercise'
require 'typingtutor/runner'
